### ISSUE TITLE
Error loading checkpoint_mir-1k.pth

### ISSUE THREAD

**Issue by yqzhishen** [WX-Wei/HarmoF0#1]
When loading `checkpoint_mir-1k.pth` in the `/harmof0/checkpoints/` directory, the following error was thrown:
> RuntimeError: Error(s) in loading state_dict for HarmoF0:
        size mismatch for block_2.0.weight: copying a param with shape torch.Size([64, 32, 1, 3]) from checkpoint, the shape in current model is torch.Size([64, 32, 3, 3]).
        size mismatch for block_3.0.weight: copying a param with shape torch.Size([128, 64, 1, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
        size mismatch for block_4.0.weight: copying a param with shape torch.Size([128, 128, 1, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).

It seems that checkpoint has different network dimensions from the default one. Is that checkpoint still available?

**Comment by WX-Wei** [comment]
The checkpoint mir-1k.pth is updated. It should work now.
